modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/MoHuia/Better_Looting-Architectury/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "better_looting"
version = "${version}"
displayName = "Better Looting"
authors = "MoHuia"
logoFile = "icon.png"
displayURL = "https://github.com/MoHuia/Better_Looting-Architectury"
description = '''
Tired of being a walking vacuum? Try RPG-style immersive loot management.
'''


[[dependencies.better_looting]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_looting]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_looting]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
